version: "3.5"

services:
  webui:
    build:
      context: webui
    container_name: openwebui-cpu.ollama-openwebui.dnp.dappnode.eth
  ollama:
    build:
      context: ollama
    container_name: ollama-cpu.ollama-openwebui.dnp.dappnode.eth
